import './globals.css'
import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'
import Image from 'next/image'

import bg from '@/assets/bg.png'

const ibm = IBM_Plex_Sans({ subsets: ['latin'], variable: '--font-sans', weight: '400' })

export const metadata: Metadata = {
  title: 'AI Platform',
  description: 'Generated by create next app by Sérgio Sanchez',
}

const Background = () => {
  return (
    <Image
      src={bg}
      alt='blue background'
      quality={100}
      fill
      sizes='100vh'
      style={{
        objectFit: 'cover',
        zIndex: '-20',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat',
      }}
      className="transition-all duration-300"
    />
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` ${ibm.variable} font-sans h-screen flex items-center justify-center p-2 overflow-hidden`}>
        <Background />
        {children}
      </body>
    </html>
  )
}
